### ISSUE TITLE
Modulo express: not found

### ISSUE THREAD

**Issue by nanotime** [arturomtm/nodejskoans#6]
Pues sí, resulta que justamente ese módulo tan importante no se encuentra en el ejercicio de express. 

Estuve pasando el test con Jasmine, también con karma y ahora corriendo node app.js y nope, nada, me dice que el módulo de express no se encuentra.

Pensé que era mi error y que no tenía instalado express, pero si está globalmente instalado en /usr/local/lib/node_modules. De todos modos dejo los logs aunque sean sencillitos: 

Jasmine:

```
Exception loading: /home/nano/Dev/NodeKoans/5_express/objetivo#1/spec/express-koans.spec.js
{ [Error: Cannot find module 'express'] code: 'MODULE_NOT_FOUND' }

```

Node:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/nano/Dev/NodeKoans/5_express/objetivo#1/express-koans.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

```

Puede que sea un error mio, pero soy bastante novato y estoy viendo por donde estoy metiendo la pata, sino, igual puede ser información que sirva para mejorar el libro en todo caso.

Gracias por el recurso!

**Comment by Chofoteddy** [comment]
De hecho para poder correr las aplicaciones y pruebas se requiere que tengas instalado `express`, `socket-io` y `jamine-node`.

    npm -g install express@3.0.0 socket-io@0.9 jasmine-node
